import React, {useContext, useEffect} from 'react';
import {Dimensions, Image, View} from 'react-native';
import Carousel from 'react-native-snap-carousel';
import {HomeProps} from '../../types/Navigation/navigation';
import {COLORS} from '../../theme';
import {ICONS, IMAGES} from '../../assets';

const {width: WIDTH} = Dimensions.get('window');

import {Button, WeatherCard, Page, TopInfo} from '../../components';
import styles from './styles';
import WeatherContext from '../../contexts/weather';
import {THourForecast} from '../../types';

const Home = ({navigation}: HomeProps) => {
  const {dayWeather, loadDayWeather} = useContext(WeatherContext);

  useEffect(() => {
    loadDayWeather('Brasília', '2021-06-05');
  }, [loadDayWeather]);

  const teste = {
    astro: {
      moon_illumination: '21',
      moon_phase: 'Waning Crescent',
      moonrise: '02:33 AM',
      moonset: '02:42 PM',
      sunrise: '06:33 AM',
      sunset: '05:47 PM',
    },
    date: '2021-06-05',
    date_epoch: 1622851200,
    day: {
      avghumidity: 53,
      avgtemp_c: 20.5,
      avgtemp_f: 68.9,
      avgvis_km: 10,
      avgvis_miles: 6,
      condition: {
        code: 1003,
        icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
        text: 'Partly cloudy',
      },
      daily_chance_of_rain: '0',
      daily_chance_of_snow: '0',
      daily_will_it_rain: 0,
      daily_will_it_snow: 0,
      maxtemp_c: 26.6,
      maxtemp_f: 79.9,
      maxwind_kph: 19.1,
      maxwind_mph: 11.9,
      mintemp_c: 14.7,
      mintemp_f: 58.5,
      totalprecip_in: 0,
      totalprecip_mm: 0,
      uv: 8,
    },
    hour: [
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 3,
        condition: [Object],
        dewpoint_c: 6.7,
        dewpoint_f: 44.1,
        feelslike_c: 18.4,
        feelslike_f: 65.1,
        gust_kph: 17.3,
        gust_mph: 10.7,
        heatindex_c: 18.4,
        heatindex_f: 65.1,
        humidity: 46,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 18.4,
        temp_f: 65.1,
        time: '2021-06-05 00:00',
        time_epoch: 1622862000,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 106,
        wind_dir: 'ESE',
        wind_kph: 8.3,
        wind_mph: 5.1,
        windchill_c: 18.4,
        windchill_f: 65.1,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 5,
        condition: [Object],
        dewpoint_c: 7.5,
        dewpoint_f: 45.5,
        feelslike_c: 17.7,
        feelslike_f: 63.9,
        gust_kph: 19.8,
        gust_mph: 12.3,
        heatindex_c: 17.7,
        heatindex_f: 63.9,
        humidity: 52,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 17.7,
        temp_f: 63.9,
        time: '2021-06-05 01:00',
        time_epoch: 1622865600,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 97,
        wind_dir: 'E',
        wind_kph: 10.1,
        wind_mph: 6.3,
        windchill_c: 17.7,
        windchill_f: 63.9,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 7,
        condition: [Object],
        dewpoint_c: 8.3,
        dewpoint_f: 46.9,
        feelslike_c: 16.9,
        feelslike_f: 62.4,
        gust_kph: 22.3,
        gust_mph: 13.9,
        heatindex_c: 16.9,
        heatindex_f: 62.4,
        humidity: 57,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 16.9,
        temp_f: 62.4,
        time: '2021-06-05 02:00',
        time_epoch: 1622869200,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 87,
        wind_dir: 'E',
        wind_kph: 11.5,
        wind_mph: 7.2,
        windchill_c: 16.9,
        windchill_f: 62.4,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 8,
        condition: [Object],
        dewpoint_c: 9.1,
        dewpoint_f: 48.4,
        feelslike_c: 16.2,
        feelslike_f: 61.2,
        gust_kph: 24.8,
        gust_mph: 15.4,
        heatindex_c: 16.2,
        heatindex_f: 61.2,
        humidity: 63,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 16.2,
        temp_f: 61.2,
        time: '2021-06-05 03:00',
        time_epoch: 1622872800,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 77,
        wind_dir: 'ENE',
        wind_kph: 13.3,
        wind_mph: 8.3,
        windchill_c: 16.2,
        windchill_f: 61.2,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 9,
        condition: [Object],
        dewpoint_c: 9.2,
        dewpoint_f: 48.6,
        feelslike_c: 15.4,
        feelslike_f: 59.7,
        gust_kph: 24.8,
        gust_mph: 15.4,
        heatindex_c: 15.7,
        heatindex_f: 60.3,
        humidity: 65,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 15.7,
        temp_f: 60.3,
        time: '2021-06-05 04:00',
        time_epoch: 1622876400,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 78,
        wind_dir: 'ENE',
        wind_kph: 13,
        wind_mph: 8.1,
        windchill_c: 15.4,
        windchill_f: 59.7,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 10,
        condition: [Object],
        dewpoint_c: 9.2,
        dewpoint_f: 48.6,
        feelslike_c: 14.7,
        feelslike_f: 58.5,
        gust_kph: 24.5,
        gust_mph: 15.2,
        heatindex_c: 15.2,
        heatindex_f: 59.4,
        humidity: 68,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1019,
        temp_c: 15.2,
        temp_f: 59.4,
        time: '2021-06-05 05:00',
        time_epoch: 1622880000,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 78,
        wind_dir: 'ENE',
        wind_kph: 13,
        wind_mph: 8.1,
        windchill_c: 14.7,
        windchill_f: 58.5,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 11,
        condition: [Object],
        dewpoint_c: 9.3,
        dewpoint_f: 48.7,
        feelslike_c: 13.9,
        feelslike_f: 57,
        gust_kph: 24.5,
        gust_mph: 15.2,
        heatindex_c: 14.7,
        heatindex_f: 58.5,
        humidity: 70,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1019,
        temp_c: 14.7,
        temp_f: 58.5,
        time: '2021-06-05 06:00',
        time_epoch: 1622883600,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 79,
        wind_dir: 'E',
        wind_kph: 12.6,
        wind_mph: 7.8,
        windchill_c: 13.9,
        windchill_f: 57,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 12,
        condition: [Object],
        dewpoint_c: 10,
        dewpoint_f: 50,
        feelslike_c: 15.7,
        feelslike_f: 60.3,
        gust_kph: 23.8,
        gust_mph: 14.8,
        heatindex_c: 16.3,
        heatindex_f: 61.3,
        humidity: 67,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1019,
        temp_c: 16.3,
        temp_f: 61.3,
        time: '2021-06-05 07:00',
        time_epoch: 1622887200,
        uv: 5,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 75,
        wind_dir: 'ENE',
        wind_kph: 14.8,
        wind_mph: 9.2,
        windchill_c: 15.7,
        windchill_f: 60.3,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 13,
        condition: [Object],
        dewpoint_c: 10.8,
        dewpoint_f: 51.4,
        feelslike_c: 17.6,
        feelslike_f: 63.7,
        gust_kph: 22.7,
        gust_mph: 14.1,
        heatindex_c: 17.8,
        heatindex_f: 64,
        humidity: 63,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1020,
        temp_c: 17.8,
        temp_f: 64,
        time: '2021-06-05 08:00',
        time_epoch: 1622890800,
        uv: 5,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 71,
        wind_dir: 'ENE',
        wind_kph: 16.9,
        wind_mph: 10.5,
        windchill_c: 17.6,
        windchill_f: 63.7,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 15,
        condition: [Object],
        dewpoint_c: 11.5,
        dewpoint_f: 52.7,
        feelslike_c: 19.4,
        feelslike_f: 66.9,
        gust_kph: 22,
        gust_mph: 13.6,
        heatindex_c: 19.4,
        heatindex_f: 66.9,
        humidity: 60,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1020,
        temp_c: 19.4,
        temp_f: 66.9,
        time: '2021-06-05 09:00',
        time_epoch: 1622894400,
        uv: 5,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 67,
        wind_dir: 'ENE',
        wind_kph: 19.1,
        wind_mph: 11.9,
        windchill_c: 19.4,
        windchill_f: 66.9,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 14,
        condition: [Object],
        dewpoint_c: 11.7,
        dewpoint_f: 53.1,
        feelslike_c: 21.2,
        feelslike_f: 70.2,
        gust_kph: 21.2,
        gust_mph: 13.2,
        heatindex_c: 21.4,
        heatindex_f: 70.5,
        humidity: 55,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1020,
        temp_c: 21.2,
        temp_f: 70.2,
        time: '2021-06-05 10:00',
        time_epoch: 1622898000,
        uv: 6,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 67,
        wind_dir: 'ENE',
        wind_kph: 18.4,
        wind_mph: 11.4,
        windchill_c: 21.2,
        windchill_f: 70.2,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 14,
        condition: [Object],
        dewpoint_c: 12,
        dewpoint_f: 53.6,
        feelslike_c: 23.5,
        feelslike_f: 74.3,
        gust_kph: 20.2,
        gust_mph: 12.5,
        heatindex_c: 23.5,
        heatindex_f: 74.3,
        humidity: 50,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1019,
        temp_c: 23,
        temp_f: 73.4,
        time: '2021-06-05 11:00',
        time_epoch: 1622901600,
        uv: 6,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 66,
        wind_dir: 'ENE',
        wind_kph: 17.6,
        wind_mph: 11,
        windchill_c: 23,
        windchill_f: 73.4,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 14,
        condition: [Object],
        dewpoint_c: 12.2,
        dewpoint_f: 54,
        feelslike_c: 25.5,
        feelslike_f: 77.9,
        gust_kph: 19.4,
        gust_mph: 12.1,
        heatindex_c: 25.5,
        heatindex_f: 77.9,
        humidity: 45,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.6,
        pressure_mb: 1019,
        temp_c: 24.8,
        temp_f: 76.6,
        time: '2021-06-05 12:00',
        time_epoch: 1622905200,
        uv: 6,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 65,
        wind_dir: 'ENE',
        wind_kph: 16.9,
        wind_mph: 10.5,
        windchill_c: 24.8,
        windchill_f: 76.6,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 25,
        condition: [Object],
        dewpoint_c: 11.4,
        dewpoint_f: 52.5,
        feelslike_c: 25.7,
        feelslike_f: 78.3,
        gust_kph: 17.3,
        gust_mph: 10.7,
        heatindex_c: 25.7,
        heatindex_f: 78.3,
        humidity: 42,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 25.4,
        temp_f: 77.7,
        time: '2021-06-05 13:00',
        time_epoch: 1622908800,
        uv: 7,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 59,
        wind_dir: 'ENE',
        wind_kph: 14.8,
        wind_mph: 9.2,
        windchill_c: 25.4,
        windchill_f: 77.7,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 36,
        condition: [Object],
        dewpoint_c: 10.7,
        dewpoint_f: 51.3,
        feelslike_c: 26,
        feelslike_f: 78.8,
        gust_kph: 14.8,
        gust_mph: 9.2,
        heatindex_c: 26,
        heatindex_f: 78.8,
        humidity: 38,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1016,
        temp_c: 26,
        temp_f: 78.8,
        time: '2021-06-05 14:00',
        time_epoch: 1622912400,
        uv: 7,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 53,
        wind_dir: 'NE',
        wind_kph: 13,
        wind_mph: 8.1,
        windchill_c: 26,
        windchill_f: 78.8,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 46,
        condition: [Object],
        dewpoint_c: 9.9,
        dewpoint_f: 49.8,
        feelslike_c: 26.2,
        feelslike_f: 79.2,
        gust_kph: 12.6,
        gust_mph: 7.8,
        heatindex_c: 26.2,
        heatindex_f: 79.2,
        humidity: 35,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1015,
        temp_c: 26.6,
        temp_f: 79.9,
        time: '2021-06-05 15:00',
        time_epoch: 1622916000,
        uv: 7,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 47,
        wind_dir: 'NE',
        wind_kph: 10.8,
        wind_mph: 6.7,
        windchill_c: 26.6,
        windchill_f: 79.9,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 46,
        condition: [Object],
        dewpoint_c: 10.2,
        dewpoint_f: 50.4,
        feelslike_c: 25.6,
        feelslike_f: 78.1,
        gust_kph: 11.9,
        gust_mph: 7.4,
        heatindex_c: 25.6,
        heatindex_f: 78.1,
        humidity: 39,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1016,
        temp_c: 25.2,
        temp_f: 77.4,
        time: '2021-06-05 16:00',
        time_epoch: 1622919600,
        uv: 7,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 58,
        wind_dir: 'ENE',
        wind_kph: 9,
        wind_mph: 5.6,
        windchill_c: 25.2,
        windchill_f: 77.4,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 45,
        condition: [Object],
        dewpoint_c: 10.6,
        dewpoint_f: 51.1,
        feelslike_c: 25.1,
        feelslike_f: 77.2,
        gust_kph: 11.2,
        gust_mph: 6.9,
        heatindex_c: 25.1,
        heatindex_f: 77.2,
        humidity: 44,
        is_day: 1,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1016,
        temp_c: 23.8,
        temp_f: 74.8,
        time: '2021-06-05 17:00',
        time_epoch: 1622923200,
        uv: 6,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 69,
        wind_dir: 'ENE',
        wind_kph: 7.6,
        wind_mph: 4.7,
        windchill_c: 23.8,
        windchill_f: 74.8,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 44,
        condition: [Object],
        dewpoint_c: 10.9,
        dewpoint_f: 51.6,
        feelslike_c: 24.5,
        feelslike_f: 76.1,
        gust_kph: 10.4,
        gust_mph: 6.5,
        heatindex_c: 24.5,
        heatindex_f: 76.1,
        humidity: 48,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1016,
        temp_c: 22.4,
        temp_f: 72.3,
        time: '2021-06-05 18:00',
        time_epoch: 1622926800,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 81,
        wind_dir: 'E',
        wind_kph: 5.8,
        wind_mph: 3.6,
        windchill_c: 22.4,
        windchill_f: 72.3,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 40,
        condition: [Object],
        dewpoint_c: 11.2,
        dewpoint_f: 52.2,
        feelslike_c: 24.5,
        feelslike_f: 76.1,
        gust_kph: 12.2,
        gust_mph: 7.6,
        heatindex_c: 24.5,
        heatindex_f: 76.1,
        humidity: 50,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1017,
        temp_c: 22,
        temp_f: 71.6,
        time: '2021-06-05 19:00',
        time_epoch: 1622930400,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 90,
        wind_dir: 'E',
        wind_kph: 7.2,
        wind_mph: 4.5,
        windchill_c: 22,
        windchill_f: 71.6,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 36,
        condition: [Object],
        dewpoint_c: 11.5,
        dewpoint_f: 52.7,
        feelslike_c: 21.7,
        feelslike_f: 71.1,
        gust_kph: 13.7,
        gust_mph: 8.5,
        heatindex_c: 24.4,
        heatindex_f: 75.9,
        humidity: 53,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1017,
        temp_c: 21.7,
        temp_f: 71.1,
        time: '2021-06-05 20:00',
        time_epoch: 1622934000,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 99,
        wind_dir: 'E',
        wind_kph: 8.3,
        wind_mph: 5.1,
        windchill_c: 21.7,
        windchill_f: 71.1,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 31,
        condition: [Object],
        dewpoint_c: 11.8,
        dewpoint_f: 53.2,
        feelslike_c: 21.3,
        feelslike_f: 70.3,
        gust_kph: 15.5,
        gust_mph: 9.6,
        heatindex_c: 24.4,
        heatindex_f: 75.9,
        humidity: 55,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 21.3,
        temp_f: 70.3,
        time: '2021-06-05 21:00',
        time_epoch: 1622937600,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 108,
        wind_dir: 'ESE',
        wind_kph: 9.7,
        wind_mph: 6,
        windchill_c: 21.3,
        windchill_f: 70.3,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 33,
        condition: [Object],
        dewpoint_c: 12,
        dewpoint_f: 53.6,
        feelslike_c: 20.6,
        feelslike_f: 69.1,
        gust_kph: 14.4,
        gust_mph: 8.9,
        heatindex_c: 22.7,
        heatindex_f: 72.9,
        humidity: 58,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 20.6,
        temp_f: 69.1,
        time: '2021-06-05 22:00',
        time_epoch: 1622941200,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 110,
        wind_dir: 'ESE',
        wind_kph: 8.6,
        wind_mph: 5.4,
        windchill_c: 20.6,
        windchill_f: 69.1,
      },
      {
        chance_of_rain: '0',
        chance_of_snow: '0',
        cloud: 34,
        condition: [Object],
        dewpoint_c: 12.2,
        dewpoint_f: 54,
        feelslike_c: 19.9,
        feelslike_f: 67.8,
        gust_kph: 13.3,
        gust_mph: 8.3,
        heatindex_c: 20.9,
        heatindex_f: 69.6,
        humidity: 62,
        is_day: 0,
        precip_in: 0,
        precip_mm: 0,
        pressure_in: 30.5,
        pressure_mb: 1018,
        temp_c: 19.9,
        temp_f: 67.8,
        time: '2021-06-05 23:00',
        time_epoch: 1622944800,
        uv: 1,
        vis_km: 10,
        vis_miles: 6,
        will_it_rain: 0,
        will_it_snow: 0,
        wind_degree: 112,
        wind_dir: 'ESE',
        wind_kph: 7.6,
        wind_mph: 4.7,
        windchill_c: 19.9,
        windchill_f: 67.8,
      },
    ],
  };

  if (!dayWeather) {
    return <View />;
  }
  return (
    <Page primaryColor={COLORS.BLUE.NORMAL} secondaryColor={COLORS.BLUE.LIGHT}>
      <Button
        image={ICONS.settings}
        style={styles.button}
        onPress={() => navigation.push('Configuration')}
      />
      <TopInfo
        topText="Brasília, DF"
        centerText={`${dayWeather.current.temp_c}º`}
        bottomText="Hoje, 6 de junho"
      />
      <View style={styles.weatherImage}>
        <Image source={IMAGES.sunCloud} />
      </View>
      <View style={styles.carousel}>
        {dayWeather?.forecast?.forecastday[0]?.hour && (
          <Carousel
            inactiveSlideScale={0.85}
            sliderWidth={WIDTH}
            itemWidth={WIDTH / 2}
            data={dayWeather?.forecast?.forecastday[0].hour}
            renderItem={({item}: {item: THourForecast}) => (
              <WeatherCard
                hour="13:00"
                image={ICONS.sun}
                temp={`${item.temp_c}º`}
                humidity={`${item.humidity}%`}
              />
            )}
          />
        )}
      </View>
    </Page>
  );
};

export default Home;
